name: Create Content
on:
  workflow_dispatch:
    inputs:
      issue_number:
        description: '記事のIssue番号'
        required: true
        type: string

permissions:
    contents: write
    pull-requests: write

jobs:
  create-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set name and email to Git
        run: |
          git config --local user.name github-actions[bot]
          git config --local user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Create and switch work branch
        id: create_work_branch
        run: |
          git switch -c "article/${{ github.event.inputs.issue_number }}"
          echo "work_branch_name=$WORK_BRANCH_NAME" >> $GITHUB_OUTPUT

      - name: Create Article
        id: create_article
        run: |
          npm install
          npx qiita new ${{ github.event.inputs.issue_number }}_article

      - name: Create pull request
        run: |
          gh --version
          gh pr create \
            -- title "Create ${{ github.event.input.issue_number }}" \
            -- body "Closed #${{ github.event.input.issue_number }}"
            --base "${{ github.event.repository.default_branch }}" \
            --head "${{ steps.create_work_branch.outputs.work_branch_name }}" \
            --draft
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
